### PR TITLE
Sign up external api and get

### PR DESCRIPTION
**Pull request by omerozdemir1**
- Check username exists searchbox is added
- Random username is generated via external API
- Get method can be triggered via URL
- Warning is given if username which is wanted to be registered already exists in database

### CODE REVIEW

**Review by mstfatay — COMMENTED** [review]
The changes look good. However, there are conflicts, you should solve them.

**Review by egetaga — COMMENTED** [review]
Reviewed your code. After solving the merge conflicts on your part, nothing seems to be problematic. But, first

- You need to be solving the conflict.

**Review by egetaga — APPROVED** [review]
I reviewed your changes and it seems to be working just fine. I am approving the changes.

**Review by harunerkurt — APPROVED** [review]
Code has been reviewed. Tested code in local, I approve as there is no problem

**Pull request merged**
