### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by hseyyidkaplan**
I edited my name and added my wiki page link.

### CODE REVIEW

**Comment by egetaga** [comment]
There are conflicts on your PR. Please solve them before merging into master.

**Comment by hseyyidkaplan** [comment]
@kamilkorkut Could you please check this pull request?

**Comment by hseyyidkaplan** [comment]
@kamilkorkut Could you please check this pull request?

**Comment by hseyyidkaplan** [comment]
@kamilkorkut Could you please check this pull request?

**Review by kamilkorkut — APPROVED** [review]
I reviewed the changes and it seems okay.

**Pull request merged**
