### PR TITLE
Teacher Course Statistics Code

### PR DESCRIPTION
**Pull request by harunerkurt**
Teacher course statistics code is written. 
Urls have been edited.
teacher_course_statistics.py code is written and tested.
teacher_course_statistics.html code is written and tested.

### CODE REVIEW

**Comment by kadirgokhann** [comment]
I see that you are making additions to the database. There doesn't seem to be a problem, but you seem to be making changes to the .env file. I think we need to fix it.

**Comment by kadirgokhann** [comment]
Others look fine.

**Comment by harunerkurt** [comment]
The readme.md file has been updated as it was in the master.

**Review by omerozdemir1 — CHANGES_REQUESTED** [review]
image

I tried your code. It works as expected. Maybe you can put a label near to submit button where we see (rating/rate_count). For example, if rating is 10 and rate_count is 2, we should see 5 which is the average rating of that course.
Other than that, Well done.

**Review by acyishere — APPROVED** [review]
reviewed.

**Review by acyishere — DISMISSED** [review]
pullable.

**Comment by kadirgokhann** [comment]
cool

**Review by omerozdemir1 — APPROVED** [review]
I reviewed your code. Everything seems perfect. Thanks!

**Pull request merged**
